apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulnerable-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Scarfacemoignon/hackathon_ovh_team7.git
    targetRevision: main
    path: apps/vulnerable-app/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true      # supprime ce qui a disparu de Git
      selfHeal: true    # répare le drift manuel — seul environnement où l'IA peut corriger
    syncOptions:
      - CreateNamespace=true
